### ISSUE TITLE
ModuleNotFoundError: No module named 'proxylist'

### ISSUE THREAD

**Issue by DevendarReddyDarukumalli** [Matrix07ksa/Brute_Force#1]
Traceback (most recent call last):
  File "Brute_Force.py", line 6, in <module>
    from proxylist import ProxyList
ModuleNotFoundError: No module named 'proxylist'

**Comment by Matrix07ksa** [comment]
pip install proxylist
😊

**Comment by DevendarReddyDarukumalli** [comment]
Requirement already satisfied: proxylist in /usr/local/lib/python2.7/dist-packages (0.1.4)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from proxylist) (1.12.0)

**Comment by kiriko31** [comment]
bonjour , meme probléme 
Traceback (most recent call last):
  File "Brute_Force.py", line 6, in <module>
    from proxylist import ProxyList
ModuleNotFoundError: No module named 'proxylist'

**Comment by Matrix07ksa** [comment]
Use python3
install proxylist 
install mechanize
😊

**Comment by ahmedmhmdn** [comment]
same problem it didnt work for me 



<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
root@kali:~/Brute_Force# pip install proxylist
Requirement already satisfied: proxylist in /usr/local/lib/python2.7/dist-packages (0.1.4)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from proxylist) (1.12.0)
root@kali:~/Brute_Force# pip install mechanize
Requirement already satisfied: mechanize in /usr/lib/python2.7/dist-packages (0.2.5)
root@kali:~/Brute_Force# python3 Brute_Force.py -g myemail@gmail.com -l File_list
Traceback (most recent call last):
  File "Brute_Force.py", line 6, in <module>
    from proxylist import ProxyList
ModuleNotFoundError: No module named 'proxylist'
root@kali:~/Brute_Force# python3 Brute_Force.py -g myemail@gmail.com -p Password_Single
Traceback (most recent call last):
  File "Brute_Force.py", line 6, in <module>
    from proxylist import ProxyList
ModuleNotFoundError: No module named 'proxylist'
root@kali:~/Brute_Force# 
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by Matrix07ksa** [comment]
pip3 install proxylist

**Comment by DevendarReddyDarukumalli** [comment]
python3 Brute_Force.py -g fakemail@gmail.com -l File_list
Traceback (most recent call last):
  File "Brute_Force.py", line 228, in <module>
    password_list = io.open(options.list_password,"r").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'File_list'

**Comment by Matrix07ksa** [comment]
Not Found List.txt

**Comment by DevendarReddyDarukumalli** [comment]
Meaning ?

**Comment by Matrix07ksa** [comment]
There must be List

**Comment by DevendarReddyDarukumalli** [comment]
Need to create if yes where we need to create that

**Comment by nwitked** [comment]
pip3 install proxylist 
pip3 install mechanize
pip3 install mechanize 
Traceback (most recent call last):
  File "Brute_Force.py", line 72, in <module>
    brows = Browser()
NameError: name 'Browser' is not defined

**Comment by starinfinity** [comment]
Manually add proxylist package

`pip install -U proxylist`

Documentation of package
-https://pypi.org/project/proxylist/

**Comment by zprytka** [comment]
Thank you! Works like a charm!

**Comment by 4nythingsP28** [comment]
The error still happening..

pip3 install proxylist 
pip3 install mechanize
pip3 install mechanize 
Traceback (most recent call last):
  File "Brute_Force.py", line 72, in <module>
    brows = Browser()
NameError: name 'Browser' is not defined

**Comment by dheerajkumarpatel** [comment]
The error still happening..

pip3 install proxylist
pip3 install mechanize
pip3 install mechanize
Traceback (most recent call last):
File "Brute_Force.py", line 72, in
brows = Browser()
NameError: name 'Browser' is not defined

**Comment by starinfinity** [comment]
have you tried installing proxylist package manually ?

**Comment by 3ilmru** [comment]
hey can you help me with this error

>python3 Brute_Force.py -g engadel933@gmail.com -l File_list


Traceback (most recent call last):
  File "Brute_Force.py", line 272, in <module>
    password_list = io.open(options.list_password, "r").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'File_list'

**Comment by 3ilmru** [comment]
hey can you help me with this error

python3 Brute_Force.py -g Account@gmail.com -l File_list

Traceback (most recent call last):
File "Brute_Force.py", line 272, in
password_list = io.open(options.list_password, "r").readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'File_list'

**Comment by starinfinity** [comment]
> hey can you help me with this error
> 
> python3 Brute_Force.py -g [Account@gmail.com](mailto:Account@gmail.com) -l File_list
> 
> Traceback (most recent call last):
> File "Brute_Force.py", line 272, in
> password_list = io.open(options.list_password, "r").readlines()
> FileNotFoundError: [Errno 2] No such file or directory: 'File_list'

ummm yeah.... you need to pass a file(hash file) name as an argument instead of File_list.

**Comment by 3ilmru** [comment]
> > hey can you help me with this error
> > python3 Brute_Force.py -g [Account@gmail.com](mailto:Account@gmail.com) -l File_list
> > Traceback (most recent call last):
> > File "Brute_Force.py", line 272, in
> > password_list = io.open(options.list_password, "r").readlines()
> > FileNotFoundError: [Errno 2] No such file or directory: 'File_list'
> 
> ummm yeah.... you need to pass a file(hash file) name as an argument instead of File_list.
Thanks for your reply

I did as you said and it worked with no error but it didnt actually work, I have put in a file a list of passwords all are wrong except one which was the correct password for my account but when it came to this correct password it said the password not found !!
what am I doing wrong ??

**Comment by starinfinity** [comment]
> > > hey can you help me with this error
> > > python3 Brute_Force.py -g [Account@gmail.com](mailto:Account@gmail.com) -l File_list
> > > Traceback (most recent call last):
> > > File "Brute_Force.py", line 272, in
> > > password_list = io.open(options.list_password, "r").readlines()
> > > FileNotFoundError: [Errno 2] No such file or directory: 'File_list'
> > 
> > 
> > ummm yeah.... you need to pass a file(hash file) name as an argument instead of File_list.
> > Thanks for your reply
> 
> I did as you said and it worked with no error but it didnt actually work, I have put in a file a list of passwords all are wrong except one which was the correct password for my account but when it came to this correct password it said the password not found !!
> what am I doing wrong ??

yeah it doesn't work. Tried for both gmail and hotmail. Either it is an old program or this wan't working in first place. use this to create your own program https://embedjournal.com/how-to-use-gmail-from-terminal-linux/ .
