### ISSUE TITLE
Problem after 4 passwords tryed

### ISSUE THREAD

**Issue by Memeimagino** [Matrix07ksa/Brute_Force#11]
<<<<<<+++++Start  Attacking Email+++++>>>>>
Traceback (most recent call last):
  File "Brute_Force.py", line 232, in <module>
    smtp_srverH.login(options.hotmail,password)
  File "/usr/lib/python3.8/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.8/smtplib.py", line 635, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/lib/python3.8/smtplib.py", line 425, in docmd
    return self.getreply()
  File "/usr/lib/python3.8/smtplib.py", line 398, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

**Comment by Z1xus** [comment]
the same for me
