### ISSUE TITLE
Passport list in Millions won't be working and keeps giving an error

### ISSUE THREAD

**Issue by raphaelsimon1** [Matrix07ksa/Brute_Force#30]
Passport list in Millions won't be working and keeps giving an error

**Comment by raphaelsimon1** [comment]
File "/Users/MAINUSER/Documents/GitHub/Brute_Force/Brute_Force.py", line 266, in <module>
    smtp_srverG.login(options.gmail,password)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 642, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 432, in docmd
    return self.getreply()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
MAINUSER@FKHELLA-M-405Z Brute_Force % python3 Brute_Force.py -g ANONYMOUS@gmail.com -l rockyou.txt
Traceback (most recent call last):
  File "/Users/MAINUSER/Documents/GitHub/Brute_Force/Brute_Force.py", line 261, in <module>
    password_list = io.open(options.list_password,"r").readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 923: invalid continuation byte
MAINUSER@FKHELLA-M-405Z Brute_Force % python3 Brute_Force.py -g ANONYMOUS@gmail.com -l 10MC.txt   
Traceback (most recent call last):
  File "/Users/MAINUSER/Documents/GitHub/Brute_Force/Brute_Force.py", line 261, in <module>
    password_list = io.open(options.list_password,"r").readlines()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 2370: invalid start byte
