### ISSUE TITLE
Brute

### ISSUE THREAD

**Issue by Fkhaibari** [Matrix07ksa/Brute_Force#37]

**Comment by atqooh** [comment]
Traceback (most recent call last):
  File "/root/Brute_Force-master/Brute_Force.py", line 266, in <module>
    smtp_srverG.login(options.gmail,password)
  File "/usr/lib/python3.11/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 642, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 432, in docmd
    return self.getreply()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
