### ISSUE TITLE
NameError: global name 'ProxyList' is not defined

### ISSUE THREAD

**Issue by akmkz** [Matrix07ksa/Brute_Force#4]
Hello,
using the correct attributes, I still get this error  

> `NameError: global name 'ProxyList' is not defined`

This is the full error 
```
Exception in thread hejab:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Brute_Force.py", line 205, in twitter
    proxy()
  File "Brute_Force.py", line 86, in proxy
    pl = ProxyList()
NameError: global name 'ProxyList' is not defined

```

This is the line I use to execute 
`# python Brute_Force.py -T USERNAME -l million.txt -X proxy.txt
`

**Comment by starinfinity** [comment]
try installing proxylist package manually and then run Brute_force.py again. 

open terminal and use 
`pip install -U proxylist`

Issue is probably in 10 line
