### ISSUE TITLE
It doesn't work and I don't understand why

### ISSUE THREAD

**Issue by ChristianSestito** [Matrix07ksa/Brute_Force#46]
I'm trying to use the code on fake accounts created by me, but it keeps telling me the password is fake or giving me errors like these:

Exception in facebook thread:
Traceback (most recent call last):
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
     self.run()
   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run
     self._target(*self._args, **self._kwargs)
   File "C:\Users\sesti\OneDrive\Desktop\Brute_Force-master\Brute_Force.py", line 144, in facebook
     proxy()
   File "C:\Users\sesti\OneDrive\Desktop\Brute_Force-master\Brute_Force.py", line 87, in proxy
     pl = ProxyList()
          ^^^^^^^^^^^
TypeError: ProxyList.__init__() missing 1 required positional argument: 'source'

Can someone help me?

**Comment by Bangkah** [comment]
ya saya juga mengalami hal yang sama
